#!/bin/sh

moodledirroot="$1"

srcroot="$(readlink -fn "$(dirname "$0")")"
plugins=( 'enrol_licensing' 'local_licensing' )

if [ ! -f "${moodledirroot}/lib/moodlelib.php" ]; then
    echo "The supplied directory does not appear to contain a Moodle"
    echo "installation."
    exit 1
fi

make clean all

for plugin in ${plugins[@]}; do
    plugindir=$(sed 's%_%/%' <<<"$plugin")
    pluginzip="build/${plugin}.zip"

    plugintype="$(cut -d '_' -f 1 <<<"$plugin")"
    pluginname="$(cut -d '_' -f 2 <<<"$plugin")"

    rm -rf "${moodledirroot}/${plugindir}"
    unzip "$pluginzip"
    mv "$pluginname" "${moodledirroot}/${plugintype}"
done
